name: Build and Deploy to All Servers

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the JAR
        run: mvn clean package -DskipTests

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          for ip in ${{ secrets.SERVER_1_IP }} ${{ secrets.SERVER_2_IP }}; do
            ssh-keyscan -H $ip >> ~/.ssh/known_hosts
          done

      - name: Deploy to All Servers
        run: |
          for ip in ${{ secrets.SERVER_1_IP }} ${{ secrets.SERVER_2_IP }}; do
            echo "=== Deploying to $ip ==="

            # Copy app jar
            ssh ${{ secrets.SERVER_USER }}@$ip "mkdir -p ~/app"
            scp target/*.jar ${{ secrets.SERVER_USER }}@$ip:~/app/app.jar

            # Copy service and nginx config
            scp deploy/myapp.service ${{ secrets.SERVER_USER }}@$ip:~/myapp.service
            scp deploy/nginx.conf ${{ secrets.SERVER_USER }}@$ip:~/nginx.conf

            # Create and copy remote setup script
            cat <<'SCRIPT' > remote-setup.sh
            #!/bin/bash
            set -e
            # Install Java if missing
            if ! command -v java >/dev/null; then
              sudo apt update
              sudo apt install -y openjdk-17-jdk
            fi
            
            # Setup systemd service
            sudo mv ~/myapp.service /etc/systemd/system/myapp.service
            sudo systemctl daemon-reload
            sudo systemctl enable myapp
            sudo systemctl restart myapp
            
            # Install NGINX if missing
            if ! command -v nginx >/dev/null; then
              sudo apt update
              sudo apt install -y nginx
            fi

            # Setup NGINX config
            sudo mv ~/nginx.conf /etc/nginx/sites-available/myapp
            sudo ln -sf /etc/nginx/sites-available/myapp /etc/nginx/sites-enabled/myapp
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            sudo systemctl reload nginx
            SCRIPT

            # Send and execute the script
            scp remote-setup.sh ${{ secrets.SERVER_USER }}@$ip:~/remote-setup.sh
            ssh ${{ secrets.SERVER_USER }}@$ip "bash ~/remote-setup.sh"

          done
